Release v1.5.3 Including fix for #947
mdbootstrap/TW-Elements pull request #1017
Opened 2021-10-09 06:31 UTC by jaitaiwan

Thank you very much for your contribution! Please make sure the followings
are checked.

- [x] Read [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] Run `npm test` to make sure it formats and build successfully
- [x] Provide the scenario this PR will address(some JSFiddles will be perfect)
- [x] Refer to concerning issues if exist

2021-10-09 06:32 UTC, jaitaiwan commented
This is a release + fix for mdbootstrap/perfect-scrollbar#41

2021-10-18 03:20 UTC, hmoffatt commented
Any release should also fix #968 for which there is also a working PR.

2021-10-25 08:04 UTC, smolenski-mikolaj requested changes

2021-10-25 08:04 UTC, smolenski-mikolaj commented on src/handlers/drag-thumb.js
> +      if (e.changedTouches.length > 1) e.preventDefault()
Please merge this conidtional operators and prevent using single-line if statements, becasue it leads to errors. 

I suggest:
```
 if (e.type.startsWith('touch') && e.changedTouches.length > 1) {
   e.preventDefault();
 }
```

2021-10-25 08:17 UTC, jaitaiwan commented
Thanks for the feedback @smolenski-mikolaj.  Implemented.

2021-10-25 08:21 UTC, merged