mtrochonowicz: Removed Bootstrap classes
mdbootstrap/TW-Elements pull request #1123
Opened 2022-11-28 11:37 UTC by Trochonovitz

2022-11-29 15:49 UTC, smolenski-mikolaj requested changes

2022-11-29 15:49 UTC, smolenski-mikolaj commented on demo/sites/bs/tooltip.html
> +    <!-- Inter font -->
It should not change. We want Roboto font finally.

2022-11-29 15:49 UTC, smolenski-mikolaj commented on src/js/bs/src/util/backdrop.js
> +    this._getElement().classList.add('h-[100vh]');
There should be a helper function to add multiple classes at once. If there's not, then we should add such a function.

2022-12-02 12:43 UTC, smolenski-mikolaj commented on src/js/mdb/dom/manipulator.js
> +  addManyClasses(element, arrayClasses) {
Please change it to `addMultipleClasses`

2022-12-06 10:21 UTC, merged

2023-02-26 23:03 UTC, jdnichollsc commented
@Trochonovitz @smolenski-mikolaj carousel SELECTOR_DATA_ACTIVE_ITEM needs to be updated as well :sweat_smile:

2023-02-27 15:10 UTC, Trochonovitz commented
> @Trochonovitz @smolenski-mikolaj carousel SELECTOR_DATA_ACTIVE_ITEM needs to be updated as well 😅

@jdnichollsc could you elaborate?

2023-02-27 15:27 UTC, jdnichollsc commented
@Trochonovitz sorry, I was wrong! I was migrating a project and I didn't see that the styles are different now, thanks for your help!